title: Kvrsh Ato
author: Kvrsh Ato
email: kvrsh.ato@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on society, science, youtube videos and podcast episodes.

# social links
twitter_username: KvrshAto 
github_username:  kvrsh
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
