title: Kvrsh Ato
author: Kvrsh Ato
email: kvrsh.ato@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My website is great and informative

# social links
twitter_username: KvrshAto # DO NOT include the @ character, or else the build will fail!
github_username:  kvrsh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
